# Change these first
owner: gitetsu # Your GitHub organization or username, where this repository lives
repo: whoogle-instances-upptime # The name of this repository

sites:
  - name: search.albony.xyz
    url: https://search.albony.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: search.garudalinux.org
    url: https://search.garudalinux.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fi.png
  - name: search.dr460nf1r3.org
    url: https://search.dr460nf1r3.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: s.tokhmi.xyz
    url: https://s.tokhmi.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: search.sethforprivacy.com
    url: https://search.sethforprivacy.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: whoogle.dcs0.hu
    url: https://whoogle.dcs0.hu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/hu.png
  - name: whoogle.esmailelbob.xyz
    url: https://whoogle.esmailelbob.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: gowogle.voring.me
    url: https://gowogle.voring.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: whoogle.privacydev.net
    url: https://whoogle.privacydev.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: wwg.vern.cc
    url: https://wg.vern.cc
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: www.indexia.gq
    url: https://www.indexia.gq
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: whoogle.hostux.net
    url: https://whoogle.hostux.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: whoogle.lunar.icu
    url: https://whoogle.lunar.icu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /whoogle-instances-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Whoogle Instances Upptime
  introTitle: Whoogle Instances Upptime
  introMessage: This status page monitors [Whoogle instances](https://github.com/benbusby/whoogle-search) for uptime.
  navbar:
    - title: Status
      href: /whoogle-instances-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
